### ISSUE TITLE
Extension fails after laptop lid has been closed

### ISSUE THREAD

**Issue by stevenpitts** [bajcmartinez/nordvpn-status#2] opened 2019-06-12 17:32 UTC
I'm new to Linux logs, so please let me know if I need to supply more information and how to do so.

Whenever I open my laptop after nordvpn-status was running, it says that the extension failed in Gnome tweaks. 

11:21:14: Laptop lid closed

12:49:00: Laptop lid opened

Figured I should let you know. Thanks! ^_^
```
13:17:24 gnome-software: failed to create an app for user/*/extensions-web/shell-extension/nordvpn_status_jcmartinez.dev/*
12:50:08 nordvpnd: 2019/06/12 12:50:08 [INFO] Wed Jun 12 12:50:08 2019 AEAD Decrypt error: bad packet ID (may be a replay): [ #2401 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
12:49:00 su: pam_unix(su:session): session closed for user maku
12:49:00 nordvpnd: 2019/06/12 12:49:00 [INFO] Wed Jun 12 12:49:00 2019 MANAGEMENT: >STATE:1560358140,CONNECTED,SUCCESS,10.8.8.6,192.230.35.134,1194,,
11:21:14 gnome-software: nordvpn_status_jcmartinez.dev has error: TypeError: The method 'parent' cannot be called
11:21:14 gnome-shell: Extension "nordvpn_status@jcmartinez.dev" had error: TypeError: The method 'parent' cannot be called
11:04:48 nordvpnd: 2019/06/12 11:04:48 [INFO] Wed Jun 12 11:04:48 2019 AEAD Decrypt error: bad packet ID (may be a replay): [ #2371 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
11:04:41 gnome-shell: Updating NordVPN Status...
11:04:13 nordvpnd: 2019/06/12 11:04:13 [INFO] Wed Jun 12 11:04:13 2019 MANAGEMENT: >STATE:1560351853,CONNECTED,SUCCESS,10.8.8.34,192.230.35.134,1194,,
11:04:11 systemd: Started NordVPN Daemon.
```

**Comment by jcmartinezdev** [comment] 2019-09-18 07:45
Thanks, and sorry for the late reply, I've been a bit busy with moving to a new country. I'll take a look into the issue, it's not a problem for my machine, can you please let me know which OS you are running.

**Comment by stevenpitts** [comment] 2019-09-18 11:40
No worries! Ubuntu 18.04

**Comment by radmedres** [comment] 2019-11-07 19:37
I had the same problem (Arch). The problem is gone after I changed the destroy function to:

    destroy() {
        this.stopTimer();
        // Call destroy on the parent
        this.indicators.destroy();
        if (typeof this.parent === "function") { 
            this.parent();
        } 
    }

**Comment by jcmartinezdev** [comment] 2019-11-08 11:39
@radmedres thanks for the contribution, I'll incorporate the changes and make a new release now.

**Closed as completed** 2019-11-08 11:41 UTC

**Comment by jcmartinezdev** [comment] 2019-11-11 10:32
This fix has now been released and can be downloaded from the extensions updates
